# Generated by Django 2.1.2 on 2018-10-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkRecodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mscore', models.IntegerField()),
                ('mdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=1)),
                ('ptitle', models.CharField(max_length=500)),
                ('pa', models.CharField(max_length=200)),
                ('pb', models.CharField(max_length=200)),
                ('pc', models.CharField(max_length=200)),
                ('pd', models.CharField(max_length=200)),
                ('pkey', models.CharField(max_length=200)),
                ('pdiff', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuser', models.CharField(max_length=100)),
                ('upass', models.CharField(max_length=100)),
                ('uaccode', models.CharField(max_length=4)),
                ('uaccodedate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='markrecodeinfo',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo'),
        ),
    ]
