# Generated by Django 2.1.2 on 2018-10-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181009_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isAction',
            field=models.BooleanField(default=False),
        ),
    ]
