# Generated by Django 2.1.2 on 2018-10-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userinfo_isaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uaccode',
            field=models.CharField(max_length=100),
        ),
    ]
