# Generated by Django 2.1.2 on 2018-10-14 02:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181014_0900'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('User', django.db.models.manager.Manager()),
            ],
        ),
    ]
